<a href="https://colab.research.google.com/github/RoshanKrO7/6sem/blob/main/DAV_Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

list_of_numbers =[12.23, 13.32, 100, 36.32]

np_array = np.array(list_of_numbers)

print(np_array)

[ 12.23  13.32 100.    36.32]


In [ ]:
matrix = np.arange(2, 11).reshape(3, 3)
print(matrix)



[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [ ]:
matrix = np.array([[7, 3, 4],
                   [1, 8, 5],
                   [9, 2, 6]])
sorted_rows = np.sort(matrix, axis=0)
sorted_columns = np.sort(matrix, axis=1)
print("Sorted rows:\n", sorted_rows)
print("\nSorted columns:\n", sorted_columns)

Sorted rows:
 [[1 2 4]
 [7 3 5]
 [9 8 6]]

Sorted columns:
 [[3 4 7]
 [1 5 8]
 [2 6 9]]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
flat_arr = arr.flatten(order='F')
print(flat_arr)


[1 4 2 5 3 6]


In [ ]:
random_ints = np.random.randint(10, 31, size=6)
print(random_ints)


[26 20 25 29 30 13]


In [ ]:
array = np.random.rand(5, 5)
min_value = np.min(array)
max_value = np.max(array)
print(array)
print("Minimum value:", min_value)
print("Maximum value:", max_value)

[[0.62370952 0.30476614 0.08917114 0.2639633  0.92170277]
 [0.38923205 0.01834754 0.35776056 0.81124226 0.33304547]
 [0.75667424 0.93585277 0.06834553 0.57638727 0.4209989 ]
 [0.02657837 0.36812911 0.22404624 0.04386418 0.2500326 ]
 [0.50670422 0.85742343 0.08649466 0.72494086 0.86615095]]
Minimum value: 0.018347537272371373
Maximum value: 0.9358527723295474
